name: Buf CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Buf CLI
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.48.0/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Lint Protobuf files
        run: buf lint

      - name: Build Protobuf files
        run: buf build
