name: Buf CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-doc:
    name: Lint, Build, and Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Ensure the desired Go version is installed

      - name: Install protoc-gen-doc
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.48.0  # Specify the Buf CLI version

      - name: Lint Protobuf files
        run: buf lint

      - name: Build Protobuf files
        run: buf build

      - name: Generate Documentation
        run: buf generate

  publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest
    needs: lint-build-doc
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.48.0  # Specify the Buf CLI version

      - name: Authenticate with Buf
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf registry login --token-stdin $BUF_TOKEN

      - name: Publish to Buf
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push
