name: Buf CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUF_TOKEN: ${{ secrets.BUF_TOKEN }}

jobs:
  lint-build-doc:
    name: Lint, Build, and Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install protoc-gen-doc
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Buf Lint, Build, and Generate
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: "proto"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          breaking-against: "https://github.com/zackiles/protobuf-postgres-extension.git#branch=main,ref=HEAD~1,subdir=proto"
          breaking: true
          lint: true
          format: true

  publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest
    needs: lint-build-doc
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Buf
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: "proto"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true