name: Buf CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Protobuf files
        run: buf lint

      - name: Build Protobuf files
        run: buf build

  publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest
    needs: lint-and-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.x

      - name: Authenticate with Buf
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf registry login --token $BUF_TOKEN

      - name: Publish to Buf
        run: buf push
